version: '3.1'
services:

    sql_server:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: sql_server
        ports:
            - 1433:1433
        networks:
            - back
        environment:
            SA_PASSWORD: MySecretPassword!
            ACCEPT_EULA: "Y"

    rabbitmq:
        image: rabbitmq:3.11.10-management
        container_name: rabbitmq
        restart: on-failure
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - back
        environment:
            - "RABBITMQ_DEFAULT_USER=guest"
            - "RABBITMQ_DEFAULT_PASS=guest"

    neo4j:
        image: neo4j:4.4-community
        container_name: neo4j
        restart: unless-stopped
        ports:
            - 7474:7474
            - 7687:7687
        volumes:
            - ./conf:/conf
            - ./data:/data
            - ./import:/import
            - ./logs:/logs
            - ./plugins:/plugins
        environment: 
            - NEO4J_dbms_memory_pagecache_size=1G
            - NEO4J_dbms.memory.heap.initial_size=1G
            - NEO4J_dbms_memory_heap_max__size=1G
            - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
            - NEO4J_apoc_export_file_enabled=true
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_apoc_import_file_use__neo4j__config=true
            - NEO4JLABS_PLUGINS='["apoc"]'
            NEO4J_AUTH: MySecretNeo4jAuthCredentials!

networks:
    back:
        driver: bridge