version: '3.1'
services:
  easyspeak_core:
    build:
      context: ./backend
      dockerfile: ./EasySpeak.Core/Dockerfile
      args:
        - PROJECT_PORT=5050
    container_name: 'easyspeak_core'
    restart: on-failure
    ports:
        - "5050:5050"
    networks:
        - back
    environment:
        ASPNETCORE_ENVIRONMENT: 'Development'
        ConnectionStrings__EasySpeakCoreDBConnection: 'Server=sql_server;Database=EasySpeakCoreDB;User ID=SA;Password=MySecretPassword!'

  easyspeak_notifier:
      build:
        context: ./backend
        dockerfile: ./EasySpeak.Notifier/Dockerfile
        args:
          - PROJECT_PORT=5070
      container_name: 'easyspeak_notifier'
      restart: on-failure
      ports:
          - "5070:5070"
      networks:
          - back
      environment:
          ASPNETCORE_ENVIRONMENT: 'Development'

  easyspeak_client:
    depends_on:
        - easyspeak_core
        - easyspeak_notifier
    build:
        context: ./frontend
        dockerfile: Dockerfile.dev
    container_name: 'easyspeak_frontend'
    restart: on-failure
    ports:
        - "4200:80"
    networks:
        - back
        - front

networks:
    back:
        driver: bridge
    front:
        driver: bridge