using System.ComponentModel;

namespace EasySpeak.Core.Common.Enums;

public enum Country: int
{
    [Description("Afghanistan")] Af = 1,
    [Description("Åland Islands")] Ax,
    [Description("Albania")] Al,
    [Description("Algeria")] Dz,
    [Description("American Samoa")] As,
    [Description("Andorra")] Ad,
    [Description("Angola")] Ao,
    [Description("Anguilla")] Ai,
    [Description("Antarctica")] Aq,
    [Description("Antigua and Barbuda")] Ag,
    [Description("Argentina")] Ar,
    [Description("Armenia")] Am,
    [Description("Aruba")] Aw,
    [Description("Australia")] Au,
    [Description("Austria")] At,
    [Description("Azerbaijan")] Az,
    [Description("Bahamas")] Bs,
    [Description("Bahrain")] Bh,
    [Description("Bangladesh")] Bd,
    [Description("Barbados")] Bb,
    [Description("Belarus")] By,
    [Description("Belgium")] Be,
    [Description("Belize")] Bz,
    [Description("Benin")] Bj,
    [Description("Bermuda")] Bm,
    [Description("Bhutan")] Bt,
    [Description("Bolivia (Plurinational State of)")] Bo,
    [Description("Bonaire, Sint Eustatius and Saba")] Bq,
    [Description("Bosnia and Herzegovina")] Ba,
    [Description("Botswana")] Bw,
    [Description("Bouvet Island")] Bv,
    [Description("Brazil")] Br,
    [Description("British Indian Ocean Territory")] Io,
    [Description("Brunei Darussalam")] Bn,
    [Description("Bulgaria")] Bg,
    [Description("Burkina Faso")] Bf,
    [Description("Burundi")] Bi,
    [Description("Cabo Verde")] Cv,
    [Description("Cambodia")] Kh,
    [Description("Cameroon")] Cm,
    [Description("Canada")] Ca,
    [Description("Cayman Islands")] Ky,
    [Description("Central African Republic")] Cf,
    [Description("Chad")] Td,
    [Description("Chile")] Cl,
    [Description("China")] Cn,
    [Description("Christmas Island")] Cx,
    [Description("Cocos (Keeling) Islands")] Cc,
    [Description("Colombia")] Co,
    [Description("Comoros")] Km,
    [Description("Congo")] Cg,
    [Description("Congo (Democratic Republic of the)")] Cd,
    [Description("Cook Islands")] Ck,
    [Description("Costa Rica")] Cr,
    [Description("Côte d'Ivoire")] Ci,
    [Description("Croatia")] Hr,
    [Description("Cuba")] Cu,
    [Description("Curaçao")] Cw,
    [Description("Cyprus")] Cy,
    [Description("Czechia")] Cz,
    [Description("Denmark")] Dk,
    [Description("Djibouti")] Dj,
    [Description("Dominica")] Dm,
    [Description("Dominican Republic")] Do,
    [Description("Ecuador")] Ec,
    [Description("Egypt")] Eg,
    [Description("El Salvador")] Sv,
    [Description("Equatorial Guinea")] Gq,
    [Description("Eritrea")] Er,
    [Description("Estonia")] Ee,
    [Description("Ethiopia")] Et,
    [Description("Falkland Islands (Malvinas)")] Fk,
    [Description("Faroe Islands")] Fo,
    [Description("Fiji")] Fj,
    [Description("Finland")] Fi,
    [Description("France")] Fr,
    [Description("French Guiana")] Gf,
    [Description("French Polynesia")] Pf,
    [Description("French Southern Territories")] Tf,
    [Description("Gabon")] Ga,
    [Description("Gambia")] Gm,
    [Description("Georgia")] Ge,
    [Description("Germany")] De,
    [Description("Ghana")] Gh,
    [Description("Gibraltar")] Gi,
    [Description("Greece")] Gr,
    [Description("Greenland")] Gl,
    [Description("Grenada")] Gd,
    [Description("Guadeloupe")] Gp,
    [Description("Guam")] Gu,
    [Description("Guatemala")] Gt,
    [Description("Guernsey")] Gg,
    [Description("Guinea")] Gn,
    [Description("Guinea-Bissau")] Gw4,
    [Description("Guyana")] Gy,
    [Description("Haiti")] Ht,
    [Description("Heard Island and McDonald Islands")] Hh,
    [Description("Holy See")] Va,
    [Description("Honduras")] Hn,
    [Description("Hong Kong")] Hk,
    [Description("Hungary")] Hu,
    [Description("Iceland")] Is,
    [Description("India")] In,
    [Description("Indonesia")] Id,
    [Description("Iran (Islamic Republic of)")] Ir,
    [Description("Iraq")] Iq,
    [Description("Ireland")] Ie,
    [Description("Isle of Man")] Im,
    [Description("Israel")] Il,
    [Description("Italy")] It,
    [Description("Jamaica")] Jm,
    [Description("Japan")] Jp,
    [Description("Jersey")] Je,
    [Description("Jordan")] Jo,
    [Description("Kazakhstan")] Kz,
    [Description("Kenya")] Ke,
    [Description("Kiribati")] Ki,
    [Description("Korea (Democratic People's Republic of)")] Kp,
    [Description("Korea (Republic of)")] Kr,
    [Description("Kuwait")] Kw,
    [Description("Kyrgyzstan")] Kg,
    [Description("Lao People's Democratic Republic")] La,
    [Description("Latvia")] Lv,
    [Description("Lebanon")] Lb,
    [Description("Lesotho")] Ls,
    [Description("Liberia")] Lr,
    [Description("Libya")] Ly,
    [Description("Liechtenstein")] Li,
    [Description("Lithuania")] Lt,
    [Description("Luxembourg")] Lu,
    [Description("Macao")] Mo,
    [Description("Macedonia (the former Yugoslav Republic of)")] Mk,
    [Description("Madagascar")] Mg,
    [Description("Malawi")] Mw,
    [Description("Malaysia")] My,
    [Description("Maldives")] Mv,
    [Description("Mali")] Ml,
    [Description("Malta")] Mt,
    [Description("Marshall Islands")] Mh,
    [Description("Martinique")] Mq,
    [Description("Mauritania")] Mr,
    [Description("Mauritius")] Mu,
    [Description("Mayotte")] Yt,
    [Description("Mexico")] Mx,
    [Description("Micronesia (Federated States of)")] Fm,
    [Description("Moldova (Republic of)")] Md,
    [Description("Monaco")] Mc,
    [Description("Mongolia")] Mn,
    [Description("Montenegro")] Me,
    [Description("Montserrat")] Ms,
    [Description("Morocco")] Ma,
    [Description("Mozambique")] Mz,
    [Description("Myanmar")] Mm,
    [Description("Namibia")] Na,
    [Description("Nauru")] Nr,
    [Description("Nepal")] Np,
    [Description("Netherlands")] Nl,
    [Description("New Caledonia")] Nc,
    [Description("New Zealand")] Nz,
    [Description("Nicaragua")] Ni,
    [Description("Niger")] Ne,
    [Description("Nigeria")] Ng,
    [Description("Niue")] Nu,
    [Description("Norfolk Island")] Nf,
    [Description("Northern Mariana Islands")] Mp,
    [Description("Norway")] No,
    [Description("Oman")] Om,
    [Description("Pakistan")] Pk,
    [Description("Palau")] Pw,
    [Description("Palestine, State of")] Ps,
    [Description("Panama")] Pa,
    [Description("Papua New Guinea")] Pg,
    [Description("Paraguay")] Py,
    [Description("Peru")] Pe,
    [Description("Philippines")] Ph,
    [Description("Pitcairn")] Pn,
    [Description("Poland")] Pl,
    [Description("Portugal")] Pt,
    [Description("Puerto Rico")] Pr,
    [Description("Qatar")] Qa,
    [Description("Réunion")] Re,
    [Description("Romania")] Ro,
    [Description("Russian Federation")] Ru,
    [Description("Rwanda")] Rw,
    [Description("Saint Barthélemy")] Bl,
    [Description("Saint Helena, Ascension and Tristan da Cunha")] Sh,
    [Description("Saint Kitts and Nevis")] Kn,
    [Description("Saint Lucia")] Lc,
    [Description("Saint Martin (French part)")] Mf,
    [Description("Saint Pierre and Miquelon")] Pm,
    [Description("Saint Vincent and the Grenadines")] Vc,
    [Description("Samoa")] Ws,
    [Description("San Marino")] Sm,
    [Description("Sao Tome and Principe")] St,
    [Description("Saudi Arabia")] Sa,
    [Description("Senegal")] Sn,
    [Description("Serbia")] Rs,
    [Description("Seychelles")] Sc,
    [Description("Sierra Leone")] Sl,
    [Description("Singapore")] Sg,
    [Description("Sint Maarten (Dutch part)")] Sx,
    [Description("Slovakia")] Sk,
    [Description("Slovenia")] Si,
    [Description("Solomon Islands")] Sb,
    [Description("Somalia")] So,
    [Description("South Africa")] Za,
    [Description("South Georgia and the South Sandwich Islands")] Gs,
    [Description("South Sudan")] Ss,
    [Description("Spain")] Es,
    [Description("Sri Lanka")] Lk,
    [Description("Sudan")] Sd,
    [Description("Suriname")] Sr,
    [Description("Svalbard and Jan Mayen")] Sj,
    [Description("Swaziland")] Sz,
    [Description("Sweden")] Se,
    [Description("Switzerland")] Ch,
    [Description("Syrian Arab Republic")] Sy,
    [Description("Taiwan, Province of China[a]")] Tw,
    [Description("Tajikistan")] Tj,
    [Description("Tanzania, United Republic of")] Tz,
    [Description("Thailand")] Th,
    [Description("Timor-Leste")] Tl,
    [Description("Togo")] Tg,
    [Description("Tokelau")] Tk,
    [Description("Tonga")] To,
    [Description("Trinidad and Tobago")] Tt,
    [Description("Tunisia")] Tn,
    [Description("Turkey")] Tr,
    [Description("Turkmenistan")] Tm,
    [Description("Turks and Caicos Islands")] Tc,
    [Description("Tuvalu")] Tv,
    [Description("Uganda")] Ug,
    [Description("Ukraine")] Ua,
    [Description("United Arab Emirates")] Ae,
    [Description("United Kingdom of Great Britain and Northern Ireland")] Gb,
    [Description("United States of America")] Us,
    [Description("United States Minor Outlying Islands")] Um,
    [Description("Uruguay")] Uy,
    [Description("Uzbekistan")] Uz,
    [Description("Vanuatu")] Vu,
    [Description("Venezuela (Bolivarian Republic of)")] Ve,
    [Description("Viet Nam")] Vn,
    [Description("Virgin Islands (British)")] Vg,
    [Description("Virgin Islands (U.S.)")] Vi,
    [Description("Wallis and Futuna")] Wf,
    [Description("Western Sahara")] Eh,
    [Description("Yemen")] Ye,
    [Description("Zambia")] Zm,
    [Description("Zimbabwe")] Zw,

}